# Generated by Django 4.0.6 on 2023-02-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_cmsteachers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsteachers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
